### ISSUE TITLE
README Clarity Issues

### ISSUE THREAD

**Issue by Chauce** [umts/prawn-rails-forms#5]
I only had one point of confusion while reading the document. It wasn't immediately clear to me how the "units" were used. It's cleared up later that `width:` denotes how many units a field takes up. I think this could be made clearer by changing: "Then we specify the fields in terms of how many units they take up[...]" to something like, "Then we specify the fields in terms of width (i.e., how many units they take up)[...]".

**Comment by dfaulken** [comment]
That's a great suggestion. Would you be able to make a pull request incorporating this change into the README?

**Comment by dfaulken** [comment]
Duplicate for #3; closes #3.
